### PR TITLE
Adding support for Liquid template includes support to HumanReadableService

### PR DESCRIPTION
**Pull request by c-schuler**
## MADiE FHIR SERVICE

Jira Ticket: N/A

### Summary

NOTE: This is my first contribution to the project. I apologize if I am not following the proper contribution guidelines.

The current HAPI FHIR version (6.6.2) used in this project has a bug for includes support in the underlying FHIR core LiquidEngine. This bug was addressed in later versions. The list of changes in this PR are summarized in the list below:

- Update to HAPI FHIR 7.4.3 (required adding in-memory cache and more recent Jackson dependencies)
- Added Measure Liquid template with includes to the templates directory
- Created test in HumanReadableServiceTest to illustrate the functionality

### All Submissions
* [ ] This PR has the JIRA linked.
* [x] Required tests are included.
* [x] No extemporaneous files are included (i.e Complied files or testing results).
* [ ] This PR is merging into the **correct branch**.
* [ ] All Documentation needed for this PR is Complete (or noted in a TODO or other Ticket).
* [ ] Any breaking changes or failing automations are noted by placing a comment on this PR.

### DevSecOps
If there is a question if this PR has a security or infrastructure impact, please contact the Security or DevOps engineer assigned to this project to discuss it further.

* [x] This PR has NO significant security impact (i.e Changing auth methods, Adding a new user type, Adding a required but vulnerable package).

### Reviewers
By Approving this PR you are attesting to the following:

*  Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose.
*  The tests appropriately test the new code, including edge cases.
*  If you have any concerns they are brought up either to the developer assigned, security engineer, or leads.

### CODE REVIEW

**Comment by jkotanchik-SB** [comment]
Neat! Thanks for pointing out the issue with HAPI. 

I did run into one minor issue while testing with templates pulled from the sample-content-ig repo. It seems the parser doesn't like the inclusion of the version comment that's in a few files:

```<!-- Liquid template version: 0.4.6 -->```

It results in the following error on execution:

```javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,39]
Message: The string "--" is not permitted within comments.
```
Either removing the comment or changing the file extension to `html` resolves the issue.

I'm guessing the Liquid engine doesn't appriciate HTML style comments as I tried replacing the HTML comment with a Liquid comment and got this error:
```
 Unknown flow control statement 'comment'
```
Guessing another HAPI issue.

**Comment by c-schuler** [comment]
Hi @jkotanchik-SB !

Yes, you cannot place HTML comments within a Liquid template. I have also run into issues using Liquid comments as well, which is likely an issue with the LiquidEngine. However, you don't need to use those comments as a [version footer](https://github.com/MeasureAuthoringTool/madie-fhir-service/pull/251/files#diff-2b25184624c959644c8c43318a08722aa9a38d00566362a7566be1a6b14916e4) has been added to the templates.

**Comment by c-schuler** [comment]
Regarding the build failure, it looks like a 401 unauthorized issue when resolving the gov.cms.madie:madie-java-models:0.6.65-SNAPSHOT. May just need to re-run the build?

**Comment by c-schuler** [comment]
@jkotanchik-SB Any updates on this? Anything I can do to help?

**Comment by jkotanchik-SB** [comment]
> @jkotanchik-SB Any updates on this? Anything I can do to help?

Thanks @c-schuler ! I'm still researching why the build fails when pulling down MADiE dependencies. Re-running doesn't help, and other PRs are able to pull down the dependencies without issue.

The other variance I can see is this PR is sourced from a fork, so I'm researching whether that has an impact.

**Comment by jkotanchik-SB** [comment]
@c-schuler Indeed, GH secrets are not passed to the Actions runner when merging from a fork (See: [GitHub actions secrets](https://github.com/s4u/maven-settings-action?tab=readme-ov-file#github-actions-secrets) and [Using secrets in a workflow](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow)).

I've verified it works locally. Will bypass checks and merge.

**Review by jkotanchik-SB — APPROVED** [review]

**Comment by jkotanchik-SB** [comment]
@c-schuler Now that we can load the templates again, the next order of business is to update the templates MADiE uses to the 0.4.5 version. 

Looking at the [v0.4.5 tag](https://github.com/cqframework/sample-content-ig/tree/v0.4.5/templates/liquid), there's a lot fewer template files than what's included in this PR. Should I be concerned about that?

**Pull request merged**
